name: belkis_seller
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  provider: ^6.0.5
  cloud_firestore: ^4.12.2

  firebase_ui_auth: ^1.4.0

  flutterfire_ui: ^0.4.3+20
  email_validator: ^2.1.17
  image_picker: ^1.0.4
  csc_picker: ^0.2.7
  firebase_storage: ^11.4.1
  animated_text_kit: ^4.2.2
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.3.0
  date_format: ^2.0.7
  intl: ^0.18.1
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Semi-Bold
      fonts:
        - asset: assets/fonts/AkayaTelivigala-Regular.ttf

    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/NotoSans-Black.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf

    - family: Bold
      fonts:
        - asset: assets/fonts/WorkSans-SemiBold.ttf
