// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZGC4LorkY67uV1n7n96YCqZZXhcHi0c',
    appId: '1:359678373942:web:f712635b81c9d17b4a6897',
    messagingSenderId: '359678373942',
    projectId: 'belkis-marketplace',
    authDomain: 'belkis-marketplace.firebaseapp.com',
    databaseURL: 'https://belkis-marketplace-default-rtdb.firebaseio.com',
    storageBucket: 'belkis-marketplace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNe29nuXAiR0Q9H6rnOm3y2DsEDaqHmgo',
    appId: '1:359678373942:android:f38b48fbbd188cc44a6897',
    messagingSenderId: '359678373942',
    projectId: 'belkis-marketplace',
    databaseURL: 'https://belkis-marketplace-default-rtdb.firebaseio.com',
    storageBucket: 'belkis-marketplace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjXZ9S-lVkPHWoFd8UmLaMWSPKxsVx9G4',
    appId: '1:359678373942:ios:0658c6e7b4fb96624a6897',
    messagingSenderId: '359678373942',
    projectId: 'belkis-marketplace',
    databaseURL: 'https://belkis-marketplace-default-rtdb.firebaseio.com',
    storageBucket: 'belkis-marketplace.appspot.com',
    androidClientId: '359678373942-h107q2tbtuokfrvdo97uvk7tfvas9uq2.apps.googleusercontent.com',
    iosClientId: '359678373942-pfh0gsl87s8nd97n0vk365nd57fpgo9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.belkisSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjXZ9S-lVkPHWoFd8UmLaMWSPKxsVx9G4',
    appId: '1:359678373942:ios:a9497b92ee597f724a6897',
    messagingSenderId: '359678373942',
    projectId: 'belkis-marketplace',
    databaseURL: 'https://belkis-marketplace-default-rtdb.firebaseio.com',
    storageBucket: 'belkis-marketplace.appspot.com',
    androidClientId: '359678373942-h107q2tbtuokfrvdo97uvk7tfvas9uq2.apps.googleusercontent.com',
    iosClientId: '359678373942-td6bm55o4uo815uusfj5s1gnoj7rpb2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.belkisSeller.RunnerTests',
  );
}
